### ISSUE TITLE
Decouple from sIT environment

### ISSUE THREAD

**Issue by christophpickl** [mihajlovicn/rest-client#1]
Currently there is a parent POM reference to some sIT internal artifact. Remove it and set necessary settings in rest-client's parent POM instead.

**Comment by christophpickl** [comment]
@mihajlovicn please review

**Comment by christophpickl** [comment]
we also should think about the package name.

maybe rename from `at.spardat.rest.client` to something like `com.github.mihajlovicn.restclient`...

**Comment by mihajlovicn** [comment]
ok, go4it.

**Comment by mihajlovicn** [comment]
i'll rename the packages, don't want sIT to kick me out because of that.

**Comment by christophpickl** [comment]
just to get the process straight as i am used to it: please dont close the issue, although i guess you accidently hit the wrong button. i'm only asking for comments (good, bad, LGTM, do this or that). as soon as i am good with the ticket, i will close and merge the branch myself ;)

and please also do not checkin any changes into "my" PR (pull request). in order to do it right (even if the benefit is close to zero but for the sake of learning and practicing) please create a new ticket and do the changes there.

**Comment by mihajlovicn** [comment]
ok, affirmitive. :)

-----Urspr�ngliche Nachricht-----
Von: Christoph Pickl [mailto:notifications@github.com] 
Gesendet: Donnerstag, 17. November 2016 14:37
An: mihajlovicn/rest-client
Cc: Mihajlovic Nenad 6303 sIT; State change
Betreff: Re: [mihajlovicn/rest-client] Decouple from sIT environment (#1) [html-removed]

just to get the process straight as i am used to it: please dont close the issue, although i guess you accidently hit the wrong button. i'm only asking for comments (good, bad, LGTM, do this or that). as soon as i am good with the ticket, i will close and merge the branch myself ;)

and please also do not checkin any changes into "my" PR (pull request). in order to do it right (even if the benefit is close to zero but for the sake of learning and practicing) please create a new ticket and do the changes there.

-- 
You are receiving this because you modified the open / close state.
Reply to this email directly or view it on GitHub:
https :  /  / github . com / mihajlovicn / rest-client / issues / 1#issuecomment-261248034

**Comment by christophpickl** [comment]
BTW: when a PR looks good to you, i am used to give it a simple "LGTM" (looks good to me) ;)

**Comment by christophpickl** [comment]
oh, you are the owner, i'm just a collaborator. so either you merge to master, or give me owner privileges :)

**Comment by christophpickl** [comment]
forget my last comment. this is the ISSUE, not the PULL REQUEST. stupid me. fuck me i am stupid.
